[2021-06-20 00:00:31,333: INFO/MainProcess] Connected to redis://redis:6379/0
[2021-06-20 00:00:31,343: INFO/MainProcess] mingle: searching for neighbors
[2021-06-20 00:00:32,375: INFO/MainProcess] mingle: all alone
[2021-06-20 00:00:32,392: WARNING/MainProcess] /usr/local/lib/python3.9/site-packages/celery/fixups/django.py:205: UserWarning: Using settings.DEBUG leads to a memory
            leak, never use this setting in production environments!
  warnings.warn('''Using settings.DEBUG leads to a memory
[2021-06-20 00:00:32,394: INFO/MainProcess] celery@eb0f99f2fad9 ready.

[2021-06-20 00:00:44,488: INFO/MainProcess] Received task: tasks.sample_tasks.create_task[570bb712-bf2c-4406-b205-07f2e83e113d]
[2021-06-20 00:00:54,479: INFO/ForkPoolWorker-7] Task tasks.sample_tasks.create_task[570bb712-bf2c-4406-b205-07f2e83e113d] succeeded in 10.023200300012832s: True
[2021-06-20 00:04:14,441: INFO/MainProcess] Connected to redis://redis:6379/0
[2021-06-20 00:04:14,456: INFO/MainProcess] mingle: searching for neighbors
[2021-06-20 00:04:15,483: INFO/MainProcess] mingle: all alone
[2021-06-20 00:04:15,498: WARNING/MainProcess] /usr/local/lib/python3.9/site-packages/celery/fixups/django.py:205: UserWarning: Using settings.DEBUG leads to a memory
            leak, never use this setting in production environments!
  warnings.warn('''Using settings.DEBUG leads to a memory
[2021-06-20 00:04:15,499: INFO/MainProcess] celery@f560c98cfb4b ready.
[2021-06-20 00:04:24,539: INFO/MainProcess] Events of group {task} enabled by remote.
[2021-06-20 00:04:53,656: INFO/MainProcess] Received task: tasks.sample_tasks.create_task[d5984ca5-f9b4-447c-997c-99b1aab1140a]  
[2021-06-20 00:04:54,260: INFO/MainProcess] Received task: tasks.sample_tasks.create_task[bb4cc1d6-2c58-4704-ae79-14815b2cba72]  
[2021-06-20 00:05:03,671: INFO/ForkPoolWorker-7] Task tasks.sample_tasks.create_task[d5984ca5-f9b4-447c-997c-99b1aab1140a] succeeded in 10.010479000004125s: True
[2021-06-20 00:05:24,261: INFO/ForkPoolWorker-8] Task tasks.sample_tasks.create_task[bb4cc1d6-2c58-4704-ae79-14815b2cba72] succeeded in 30.031653600002755s: True
[2021-06-20 00:05:38,487: INFO/MainProcess] Connected to redis://redis:6379/0
[2021-06-20 00:05:38,497: INFO/MainProcess] mingle: searching for neighbors
[2021-06-20 00:05:39,521: INFO/MainProcess] mingle: all alone
[2021-06-20 00:05:39,538: WARNING/MainProcess] /usr/local/lib/python3.9/site-packages/celery/fixups/django.py:205: UserWarning: Using settings.DEBUG leads to a memory
            leak, never use this setting in production environments!
  warnings.warn('''Using settings.DEBUG leads to a memory
[2021-06-20 00:05:39,540: INFO/MainProcess] celery@d0a86f1d75ec ready.
[2021-06-20 00:05:44,695: INFO/MainProcess] Connected to redis://redis:6379/0
[2021-06-20 00:05:44,708: INFO/MainProcess] mingle: searching for neighbors
[2021-06-20 00:05:44,724: INFO/MainProcess] Connected to redis://redis:6379/0
[2021-06-20 00:05:44,730: INFO/MainProcess] sync with celery@37b11a4c4ec6
[2021-06-20 00:05:44,735: INFO/MainProcess] mingle: searching for neighbors
[2021-06-20 00:05:44,757: INFO/MainProcess] sync with celery@6fa00eeef9b8
[2021-06-20 00:05:45,735: INFO/MainProcess] mingle: sync with 1 nodes
[2021-06-20 00:05:45,737: INFO/MainProcess] mingle: sync complete
[2021-06-20 00:05:45,752: WARNING/MainProcess] /usr/local/lib/python3.9/site-packages/celery/fixups/django.py:205: UserWarning: Using settings.DEBUG leads to a memory
            leak, never use this setting in production environments!
  warnings.warn('''Using settings.DEBUG leads to a memory
[2021-06-20 00:05:45,754: INFO/MainProcess] celery@37b11a4c4ec6 ready.
[2021-06-20 00:05:45,763: INFO/MainProcess] mingle: sync with 1 nodes
[2021-06-20 00:05:45,764: INFO/MainProcess] mingle: sync complete
[2021-06-20 00:05:45,782: WARNING/MainProcess] /usr/local/lib/python3.9/site-packages/celery/fixups/django.py:205: UserWarning: Using settings.DEBUG leads to a memory
            leak, never use this setting in production environments!
  warnings.warn('''Using settings.DEBUG leads to a memory
[2021-06-20 00:05:45,783: INFO/MainProcess] celery@6fa00eeef9b8 ready.
[2021-06-20 00:05:56,615: INFO/MainProcess] Events of group {task} enabled by remote.
[2021-06-20 00:05:56,615: INFO/MainProcess] Events of group {task} enabled by remote.
[2021-06-20 00:05:56,615: INFO/MainProcess] Events of group {task} enabled by remote.
[2021-06-20 00:06:00,919: INFO/MainProcess] Received task: tasks.sample_tasks.create_task[14709362-909e-414a-af66-f7a4bb983741]  
[2021-06-20 00:06:01,211: INFO/MainProcess] Received task: tasks.sample_tasks.create_task[d83d578c-55de-4a57-9eea-7d2b8503580f]  
[2021-06-20 00:06:01,642: INFO/MainProcess] Received task: tasks.sample_tasks.create_task[cd46304f-d62b-48e8-a832-1cdb428cd00f]  
[2021-06-20 00:06:02,065: INFO/MainProcess] Received task: tasks.sample_tasks.create_task[88c0f4a4-937c-432b-ad77-820997112a83]  
[2021-06-20 00:06:02,526: INFO/MainProcess] Received task: tasks.sample_tasks.create_task[81c4df5a-824a-4749-ac37-0140df1154aa]  
[2021-06-20 00:06:03,081: INFO/MainProcess] Received task: tasks.sample_tasks.create_task[5e009762-2662-45bf-ba33-835bac918eac]  
[2021-06-20 00:06:03,495: INFO/MainProcess] Received task: tasks.sample_tasks.create_task[2969a271-7977-46f4-87c2-c494c1f1b2c0]  
[2021-06-20 00:06:03,779: INFO/MainProcess] Received task: tasks.sample_tasks.create_task[d94f8662-4636-4fb8-8720-e22d89ed2084]  
[2021-06-20 00:06:03,963: INFO/MainProcess] Received task: tasks.sample_tasks.create_task[20d82e60-1497-49e2-99dd-cb42ac558855]  
[2021-06-20 00:06:10,933: INFO/ForkPoolWorker-7] Task tasks.sample_tasks.create_task[14709362-909e-414a-af66-f7a4bb983741] succeeded in 10.01032970000233s: True
[2021-06-20 00:06:13,101: INFO/ForkPoolWorker-2] Task tasks.sample_tasks.create_task[5e009762-2662-45bf-ba33-835bac918eac] succeeded in 10.014727000001585s: True
[2021-06-20 00:06:13,513: INFO/ForkPoolWorker-7] Task tasks.sample_tasks.create_task[2969a271-7977-46f4-87c2-c494c1f1b2c0] succeeded in 10.01371639998979s: True
[2021-06-20 00:06:13,798: INFO/ForkPoolWorker-1] Task tasks.sample_tasks.create_task[d94f8662-4636-4fb8-8720-e22d89ed2084] succeeded in 10.015402100005304s: True
[2021-06-20 00:06:13,980: INFO/ForkPoolWorker-3] Task tasks.sample_tasks.create_task[20d82e60-1497-49e2-99dd-cb42ac558855] succeeded in 10.01298400000087s: True
[2021-06-20 00:06:21,197: INFO/ForkPoolWorker-7] Task tasks.sample_tasks.create_task[d83d578c-55de-4a57-9eea-7d2b8503580f] succeeded in 20.01569169999857s: True
[2021-06-20 00:06:22,520: INFO/ForkPoolWorker-1] Task tasks.sample_tasks.create_task[81c4df5a-824a-4749-ac37-0140df1154aa] succeeded in 20.024227300003986s: True
[2021-06-20 00:06:31,642: INFO/ForkPoolWorker-8] Task tasks.sample_tasks.create_task[cd46304f-d62b-48e8-a832-1cdb428cd00f] succeeded in 30.030509000003804s: True
[2021-06-20 00:06:32,065: INFO/ForkPoolWorker-8] Task tasks.sample_tasks.create_task[88c0f4a4-937c-432b-ad77-820997112a83] succeeded in 30.029734600000666s: True
[2021-06-20 00:07:12,552: INFO/MainProcess] Connected to redis://redis:6379/0
[2021-06-20 00:07:12,563: INFO/MainProcess] mingle: searching for neighbors
[2021-06-20 00:07:13,590: INFO/MainProcess] mingle: all alone
[2021-06-20 00:07:13,608: WARNING/MainProcess] /usr/local/lib/python3.9/site-packages/celery/fixups/django.py:205: UserWarning: Using settings.DEBUG leads to a memory
            leak, never use this setting in production environments!
  warnings.warn('''Using settings.DEBUG leads to a memory
[2021-06-20 00:07:13,609: INFO/MainProcess] celery@dda5a5b50fef ready.
[2021-06-20 00:07:24,367: INFO/MainProcess] Events of group {task} enabled by remote.
[2021-06-20 00:12:11,883: INFO/MainProcess] Received task: tasks.sample_tasks.create_task[e71093ee-cca0-446c-accd-80d43ed49120]  
[2021-06-20 00:12:11,889: INFO/ForkPoolWorker-7] Task tasks.sample_tasks.create_task[e71093ee-cca0-446c-accd-80d43ed49120] succeeded in 0.0028535000019473955s: True
